-- MySQL Script generated by MySQL Workbench
-- Mon Oct  8 20:49:38 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema welovepets
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `welovepets` ;

-- -----------------------------------------------------
-- Schema welovepets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `welovepets` DEFAULT CHARACTER SET utf8 ;
USE `welovepets` ;

-- -----------------------------------------------------
-- Table `welovepets`.`user_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `welovepets`.`user_details` ;

CREATE TABLE IF NOT EXISTS `welovepets`.`user_details` (
  `userid` INT NOT NULL AUTO_INCREMENT,
  `user_first_name` VARCHAR(45) NULL,
  `user_last_name` VARCHAR(45) NULL,
  `email_id` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `last_changed_password_date` DATETIME NULL,
  `is_active` INT NULL,
  PRIMARY KEY (`userid`),
  INDEX `email_id_idx` (`email_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `welovepets`.`general_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `welovepets`.`general_details` ;

CREATE TABLE IF NOT EXISTS `welovepets`.`general_details` (
  `gd_id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NULL,
  `apt_num` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `zipcode` INT NULL,
  `full_address` VARCHAR(100) NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `user_details_userid` INT NOT NULL,
  `profile_pic_url` VARCHAR(200) NULL,
  `landline_number` VARCHAR(200) NULL,
  `mobile_number` VARCHAR(200) NULL,
  PRIMARY KEY (`gd_id`),
  INDEX `fk_general_details_user_details_idx` (`user_details_userid` ASC),
  CONSTRAINT `fk_general_details_user_details`
    FOREIGN KEY (`user_details_userid`)
    REFERENCES `welovepets`.`user_details` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `welovepets`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `welovepets`.`roles` ;

CREATE TABLE IF NOT EXISTS `welovepets`.`roles` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `welovepets`.`user_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `welovepets`.`user_type` ;

CREATE TABLE IF NOT EXISTS `welovepets`.`user_type` (
  `ust_id` INT NOT NULL AUTO_INCREMENT,
  `user_details_userid` INT NOT NULL,
  `roles_role_id` INT NOT NULL,
  PRIMARY KEY (`ust_id`),
  INDEX `fk_user_type_user_details1_idx` (`user_details_userid` ASC),
  INDEX `fk_user_type_roles1_idx` (`roles_role_id` ASC),
  CONSTRAINT `fk_user_type_user_details1`
    FOREIGN KEY (`user_details_userid`)
    REFERENCES `welovepets`.`user_details` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_type_roles1`
    FOREIGN KEY (`roles_role_id`)
    REFERENCES `welovepets`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `welovepets`.`photo_upload`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `welovepets`.`photo_upload` ;

CREATE TABLE IF NOT EXISTS `welovepets`.`photo_upload` (
  `pu_id` INT NOT NULL AUTO_INCREMENT,
  `photo_upload_url` VARCHAR(45) NULL,
  `user_details_userid` INT NOT NULL,
  PRIMARY KEY (`pu_id`),
  INDEX `fk_photo_upload_user_details1_idx` (`user_details_userid` ASC),
  INDEX `photo_url_idx` (`photo_upload_url` ASC),
  CONSTRAINT `fk_photo_upload_user_details1`
    FOREIGN KEY (`user_details_userid`)
    REFERENCES `welovepets`.`user_details` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `welovepets`.`dog_owner_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `welovepets`.`dog_owner_details` ;

CREATE TABLE IF NOT EXISTS `welovepets`.`dog_owner_details` (
  `do_details_id` INT NOT NULL AUTO_INCREMENT,
  `user_details_userid` INT NOT NULL,
  PRIMARY KEY (`do_details_id`),
  INDEX `fk_dog_owner_details_user_details1_idx` (`user_details_userid` ASC),
  CONSTRAINT `fk_dog_owner_details_user_details1`
    FOREIGN KEY (`user_details_userid`)
    REFERENCES `welovepets`.`user_details` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `welovepets`.`pet_sitter_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `welovepets`.`pet_sitter_details` ;

CREATE TABLE IF NOT EXISTS `welovepets`.`pet_sitter_details` (
  `ps_details_id` INT NOT NULL AUTO_INCREMENT,
  `user_details_userid` INT NOT NULL,
  PRIMARY KEY (`ps_details_id`),
  INDEX `fk_pet_sitter_details_user_details1_idx` (`user_details_userid` ASC),
  CONSTRAINT `fk_pet_sitter_details_user_details1`
    FOREIGN KEY (`user_details_userid`)
    REFERENCES `welovepets`.`user_details` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `welovepets`.`appointment_booking_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `welovepets`.`appointment_booking_details` ;

CREATE TABLE IF NOT EXISTS `welovepets`.`appointment_booking_details` (
  `abd_id` INT NOT NULL AUTO_INCREMENT,
  `appointment_date` VARCHAR(45) NULL,
  `dog_owner_details_do_details_id` INT NOT NULL,
  `pet_sitter_details_ps_details_id` INT NOT NULL,
  PRIMARY KEY (`abd_id`),
  INDEX `fk_appointment_booking_details_dog_owner_details1_idx` (`dog_owner_details_do_details_id` ASC),
  INDEX `fk_appointment_booking_details_pet_sitter_details1_idx` (`pet_sitter_details_ps_details_id` ASC),
  CONSTRAINT `fk_appointment_booking_details_dog_owner_details1`
    FOREIGN KEY (`dog_owner_details_do_details_id`)
    REFERENCES `welovepets`.`dog_owner_details` (`do_details_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointment_booking_details_pet_sitter_details1`
    FOREIGN KEY (`pet_sitter_details_ps_details_id`)
    REFERENCES `welovepets`.`pet_sitter_details` (`ps_details_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `welovepets`.`feedback_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `welovepets`.`feedback_details` ;

CREATE TABLE IF NOT EXISTS `welovepets`.`feedback_details` (
  `fd_id` INT NOT NULL AUTO_INCREMENT,
  `ratings` INT NULL,
  `feedback_comments` TEXT(2000) NULL,
  `dog_owner_details_do_details_id` INT NOT NULL,
  `pet_sitter_details_ps_details_id` INT NOT NULL,
  `appointment_booking_details_abd_id` INT NOT NULL,
  PRIMARY KEY (`fd_id`),
  INDEX `fk_feedback_details_dog_owner_details1_idx` (`dog_owner_details_do_details_id` ASC),
  INDEX `fk_feedback_details_pet_sitter_details1_idx` (`pet_sitter_details_ps_details_id` ASC),
  INDEX `fk_feedback_details_appointment_booking_details1_idx` (`appointment_booking_details_abd_id` ASC),
  CONSTRAINT `fk_feedback_details_dog_owner_details1`
    FOREIGN KEY (`dog_owner_details_do_details_id`)
    REFERENCES `welovepets`.`dog_owner_details` (`do_details_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_feedback_details_pet_sitter_details1`
    FOREIGN KEY (`pet_sitter_details_ps_details_id`)
    REFERENCES `welovepets`.`pet_sitter_details` (`ps_details_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_feedback_details_appointment_booking_details1`
    FOREIGN KEY (`appointment_booking_details_abd_id`)
    REFERENCES `welovepets`.`appointment_booking_details` (`abd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `welovepets`.`subscription_detials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `welovepets`.`subscription_detials` ;

CREATE TABLE IF NOT EXISTS `welovepets`.`subscription_detials` (
  `subscription_detials_id` INT NOT NULL AUTO_INCREMENT,
  `subscription_name` VARCHAR(45) NULL,
  `details` VARCHAR(300) NULL,
  `package_amt` FLOAT NULL,
  PRIMARY KEY (`subscription_detials_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `welovepets`.`subscription_purchase_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `welovepets`.`subscription_purchase_details` ;

CREATE TABLE IF NOT EXISTS `welovepets`.`subscription_purchase_details` (
  `spd_id` INT NOT NULL AUTO_INCREMENT,
  `subscription_start_date` DATETIME NULL,
  `subscription_end_date` DATETIME NULL,
  `dog_owner_details_do_details_id` INT NOT NULL,
  `subscription_detials_subscription_detials_id` INT NOT NULL,
  PRIMARY KEY (`spd_id`),
  INDEX `fk_subscription_details_dog_owner_details1_idx` (`dog_owner_details_do_details_id` ASC),
  INDEX `fk_subscription_purchase_details_subscription_detials1_idx` (`subscription_detials_subscription_detials_id` ASC),
  CONSTRAINT `fk_subscription_details_dog_owner_details1`
    FOREIGN KEY (`dog_owner_details_do_details_id`)
    REFERENCES `welovepets`.`dog_owner_details` (`do_details_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subscription_purchase_details_subscription_detials1`
    FOREIGN KEY (`subscription_detials_subscription_detials_id`)
    REFERENCES `welovepets`.`subscription_detials` (`subscription_detials_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `welovepets`.`saved_card_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `welovepets`.`saved_card_details` ;

CREATE TABLE IF NOT EXISTS `welovepets`.`saved_card_details` (
  `scd_id` INT NOT NULL AUTO_INCREMENT,
  `scd_card_number` INT NULL,
  `scd_card_owner_name` VARCHAR(45) NULL,
  `scd_card_exp_month` INT NULL,
  `scd_card_exp_year` INT NULL,
  `scd_zipcode` VARCHAR(45) NULL,
  `scd_delete_flag` INT NULL,
  `user_details_userid` INT NOT NULL,
  PRIMARY KEY (`scd_id`),
  INDEX `fk_saved_card_details_user_details1_idx` (`user_details_userid` ASC),
  CONSTRAINT `fk_saved_card_details_user_details1`
    FOREIGN KEY (`user_details_userid`)
    REFERENCES `welovepets`.`user_details` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `welovepets`.`payment_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `welovepets`.`payment_details` ;

CREATE TABLE IF NOT EXISTS `welovepets`.`payment_details` (
  `payment_details_id` INT NOT NULL AUTO_INCREMENT,
  `payment_type` VARCHAR(45) NULL,
  `payment_date` DATETIME NULL,
  `payment_amount` FLOAT NULL,
  `is_approved` TINYINT(1) NULL,
  PRIMARY KEY (`payment_details_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `welovepets`.`type_of_payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `welovepets`.`type_of_payment` ;

CREATE TABLE IF NOT EXISTS `welovepets`.`type_of_payment` (
  `top_id` INT NOT NULL AUTO_INCREMENT,
  `top_name` VARCHAR(45) NULL,
  PRIMARY KEY (`top_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `welovepets`.`payment_apportioning`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `welovepets`.`payment_apportioning` ;

CREATE TABLE IF NOT EXISTS `welovepets`.`payment_apportioning` (
  `payment_apportioning_id` INT NOT NULL AUTO_INCREMENT,
  `payment_apportioning_service_id` VARCHAR(45) NULL,
  `payment_source` VARCHAR(45) NULL,
  `payment_details_payment_details_id` INT NOT NULL,
  `type_of payment_top_id` INT NOT NULL,
  `user_details_userid` INT NOT NULL,
  PRIMARY KEY (`payment_apportioning_id`),
  INDEX `fk_payment_apportioning_payment_details1_idx` (`payment_details_payment_details_id` ASC),
  INDEX `fk_payment_apportioning_type_of payment1_idx` (`type_of payment_top_id` ASC),
  INDEX `fk_payment_apportioning_user_details1_idx` (`user_details_userid` ASC),
  CONSTRAINT `fk_payment_apportioning_payment_details1`
    FOREIGN KEY (`payment_details_payment_details_id`)
    REFERENCES `welovepets`.`payment_details` (`payment_details_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_apportioning_type_of payment1`
    FOREIGN KEY (`type_of payment_top_id`)
    REFERENCES `welovepets`.`type_of_payment` (`top_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_apportioning_user_details1`
    FOREIGN KEY (`user_details_userid`)
    REFERENCES `welovepets`.`user_details` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `welovepets`.`cash_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `welovepets`.`cash_details` ;

CREATE TABLE IF NOT EXISTS `welovepets`.`cash_details` (
  `cash_details_id` INT NOT NULL AUTO_INCREMENT,
  `cash_amt` VARCHAR(45) NULL,
  `payment_details_payment_details_id` INT NOT NULL,
  PRIMARY KEY (`cash_details_id`),
  INDEX `fk_cash_details_payment_details1_idx` (`payment_details_payment_details_id` ASC),
  CONSTRAINT `fk_cash_details_payment_details1`
    FOREIGN KEY (`payment_details_payment_details_id`)
    REFERENCES `welovepets`.`payment_details` (`payment_details_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `welovepets`.`card_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `welovepets`.`card_details` ;

CREATE TABLE IF NOT EXISTS `welovepets`.`card_details` (
  `card_details_id` INT NOT NULL AUTO_INCREMENT,
  `card_amt` FLOAT NULL,
  `payment_details_payment_details_id` INT NOT NULL,
  `saved_card_details_scd_id` INT NOT NULL,
  INDEX `fk_table2_payment_details1_idx` (`payment_details_payment_details_id` ASC),
  PRIMARY KEY (`card_details_id`),
  INDEX `fk_card_details_saved_card_details1_idx` (`saved_card_details_scd_id` ASC),
  CONSTRAINT `fk_table2_payment_details1`
    FOREIGN KEY (`payment_details_payment_details_id`)
    REFERENCES `welovepets`.`payment_details` (`payment_details_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_card_details_saved_card_details1`
    FOREIGN KEY (`saved_card_details_scd_id`)
    REFERENCES `welovepets`.`saved_card_details` (`scd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `welovepets`.`cheque_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `welovepets`.`cheque_details` ;

CREATE TABLE IF NOT EXISTS `welovepets`.`cheque_details` (
  `cheque_details_id` INT NOT NULL AUTO_INCREMENT,
  `bank_name` VARCHAR(45) NULL,
  `cheque_amount` FLOAT NULL,
  `cheque_date` DATETIME NULL,
  `payment_details_payment_details_id` INT NOT NULL,
  `cheque_routing_number` VARCHAR(45) NULL,
  `cheque_account_number` VARCHAR(45) NULL,
  `cheque_number` VARCHAR(45) NULL,
  `cheque_holder_name` VARCHAR(45) NULL,
  INDEX `fk_table3_payment_details1_idx` (`payment_details_payment_details_id` ASC),
  PRIMARY KEY (`cheque_details_id`),
  CONSTRAINT `fk_table3_payment_details1`
    FOREIGN KEY (`payment_details_payment_details_id`)
    REFERENCES `welovepets`.`payment_details` (`payment_details_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
